BOOTMAGIC_ENABLE = no		# Enable Bootmagic Lite
# MOUSEKEY_ENABLE = yes		# Mouse keys
# EXTRAKEY_ENABLE = yes		# Audio control and System control
CONSOLE_ENABLE = no			# Console for debug
# NKRO_ENABLE = yes			# USB Nkey Rollover
LTO_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OS_DETECTION_ENABLE = yes
